### ISSUE TITLE
Library crashes on exit if server or client is not started

### ISSUE THREAD

**Issue by HuxyUK** [Halichoerus/NetLibrary#11]
https://github.com/Halichoerus/NetLibrary/blob/5685d078d46c5f1fce5646768ffddb006601364d/Source/Linux/Client.cpp#L15

https://github.com/Halichoerus/NetLibrary/blob/5685d078d46c5f1fce5646768ffddb006601364d/Source/Linux/Server.cpp#L13

https://github.com/Halichoerus/NetLibrary/blob/5685d078d46c5f1fce5646768ffddb006601364d/Source/Windows/Server.cpp#L9

Looks like a simple check in each destructor solves the problem
```cpp
 if(running) { stop();  ... } 
```

**Comment by Halichoerus** [comment]
Both client/server terminate gracefully on windows/linux now.
