### ISSUE TITLE
Linux: Failed to bind socket to IP or Port

### ISSUE THREAD

**Issue by HuxyUK** [Halichoerus/NetLibrary#15]
Any idea why sometimes on launching the server, I get the following error?:

```shell
Failed to bind socket to IP or Port
Unknown error
```

It happens fairly frequently.

**Comment by Halichoerus** [comment]
Is this on linux? For some reason the socket sometimes stays open on the server exiting on linux, I couldn't seem to work out why it was doing it.

**Comment by HuxyUK** [comment]
See title of the issue ;)
We do have some users of Linux as well as myself, so it would be good to get to the bottom of this if possible.

**Comment by Halichoerus** [comment]
Ah yes, I am blind! I will look into finding a fix for it.

**Comment by Halichoerus** [comment]
Found that linux requires a shutdown() call to sockets before closing them, so this should be fixed now.
